name: "Zenerator 4 Series"

on:
  workflow_dispatch:
    inputs:
      Season:
        description: "Season"
        required: true
        type: choice
        options:
        - "01"
        - "02"
        - "03"
        - "04"
      EpNum:
        description: "EpNum"
        required: true
        type: choice
        options:
        - "01"
        - "02"
        - "03"
        - "04"
        - "05"
        - "06"
        - "07"
        - "08"
        - "09"
        - "10"
        - "11"
        - "12"
        - "13"
        - "14"
        - "15"
        - "16"
        - "17"
        - "18"
        - "19"
        - "20"
        - "21"
        - "22"
        - "23"
        - "24"
        - "25"
        - "26"

env:
  SOURCERY: ${{ secrets.SOURCERY }}
  SauceLocationOnIndex: "td:/MiraculouSauce"
  LocationOnIndex: "td:/MiraculouSourcery"
  Variant: "Series"
  Season: ${{ github.event.inputs.Season }}
  EpNum: ${{ github.event.inputs.EpNum }}
  SubLocation: "S${{ github.event.inputs.Season }}E${{ github.event.inputs.EpNum }}"
  RCLONE_CONFIG_URL: ${{ secrets.RCLONE_CONFIG_URL }}
  RCLONE_INSTALL_MIRROR: ${{ secrets.RCLONE_INSTALL_MIRROR }}
  FTOOL_ARC_URL: ${{ secrets.FTOOL_ARC_URL }}
  FTOOL_CONVERTER: ${{ secrets.FTOOL_CONVERTER }}
  FTOOL_PROBER: ${{ secrets.FTOOL_PROBER }}

jobs:

  generator:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Invoke Gatekeeper
        run: |
          if ! grep -q "${SubLocation}" "Z.EpList.txt"; then
            printf "[!] This Episode in the %s Does Not Exist, Quitting The Job.\n" "${SubLocation}"
            exit 1
          fi
      - name: EncTool Preparation
        if: ${{ success() }}
        run: |
          eval 'set -eo pipefail' 2>/dev/null
          eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY
          source ./SOURCERY &>/dev/null
          rm -f ./SOURCERY
          eval 'set -o history' 2>/dev/null
          DEOBFUS ./20-EncCh.1cbe7e5d415c
          DEOBFUS ./20-EncDl.79fef8643f7b
          DEOBFUS ./20-EncRn.db2ad0dc8ed8
      - name: Chunk+Audio Generator for ${{env.SubLocation}}
        run: |
          eval 'set -eo pipefail' 2>/dev/null
          eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY
          source ./SOURCERY &>/dev/null
          rm -f ./SOURCERY
          eval 'set -o history' 2>/dev/null
          DEOBFUS ./69-EncGen.4c3e09ffe1ba
      - name: Finishing Message
        if: ${{ success() }}
        run: |
          printf "Generator Job Successful for %s\n" "${{env.SubLocation}}"
